apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: web
    image: devgrav/otus-kubernetes-study-hw1-webserver:1.0
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: create-index-page
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh'] 
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
    - name: app
      emptyDir: {}



